INSERT INTO OWNER (ID, EMERALD_ACCOUNT) VALUES (1, 5000);
INSERT INTO PRODUCT (ID, NAME, OWNER_ID) VALUES (1, 'PRODUKT_1', 1);

INSERT INTO TOWN (ID, NAME) VALUES (1, 'Kraków');
INSERT INTO TOWN (ID, NAME) VALUES (2, 'Warszawa');
INSERT INTO TOWN (ID, NAME) VALUES (3, 'Wrocław');
INSERT INTO TOWN (ID, NAME) VALUES (4, 'Łódź');
INSERT INTO TOWN (ID, NAME) VALUES (5, 'Rzeszów');
INSERT INTO TOWN (ID, NAME) VALUES (6, 'Gdańsk');

INSERT INTO KEY_WORD (ID, NAME) VALUES (1, 'Reklama');
INSERT INTO KEY_WORD (ID, NAME) VALUES (2, 'Promocja');
INSERT INTO KEY_WORD (ID, NAME) VALUES (3, 'Event');
INSERT INTO KEY_WORD (ID, NAME) VALUES (4, 'Premium');
INSERT INTO KEY_WORD (ID, NAME) VALUES (5, 'Wyprzedaż');
INSERT INTO KEY_WORD (ID, NAME) VALUES (6, 'Kampania');



